[package]
name = "bosch_brain"
version = "0.1.0"
edition = "2021"

#[profile.dev.package.num-bigint-dig] # Fast RSA in debug mode
#opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
incremental = true
lto = "thin"

[dependencies]
sensors = { path = "sensors" }
# Async
tokio = { version = "1", features = ["libc", "bytes", "fs", "io-std", "io-util", "macros", "rt-multi-thread", "sync", "net"] }
futures = "0.3"

# Logging
log = { version = "0.4", default-features = false, features = ["std", "serde", "max_level_debug", "release_max_level_warn"] }
env_logger = { version = "0.10", default-features = false, features = ["humantime", "color"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Serial port
serialport = { version = "4", default-features = false }
mio-serial = { version = "5", default-features = false }

# TUI/keycapture
crossterm = { version = "0.25", features = ["event-stream"] }

rsa = "0.7"
digest = "0.10"
md-5 = "0.10"

ordered-float = "3"