[package]
name = "bosch_brain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["libc", "bytes", "fs", "io-std", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
tokio-serial = { version = "5.4" }
log = "0.4"
