[package]
name = "bosch_brain"
version = "0.1.0"
edition = "2021"

[profile.release]
incremental = true
lto = "thin"

[dependencies]
# Async
tokio = { version = "1", features = ["libc", "bytes", "fs", "io-std", "io-util", "macros", "rt-multi-thread", "sync", "time", "net", "mio"] }
futures = "0.3"

# Logging
log = { version = "0.4", features = ["std", "serde", "max_level_debug", "release_max_level_warn"] }
env_logger = "0.10"

# IMU
linux-embedded-hal = "0.3"
mpu6050 = "0.1.6"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Serial port
serialport = { version = "4", default-features = false }
mio-serial = { version = "5", default-features = false }

# TUI/keycapture
crossterm = { version = "0.25", features = ["event-stream"] }
