[package]
name = "sensors"
version = "1.0.0"
edition = "2021"

[dependencies]
linux-embedded-hal = "0.3"
# HC-SR04 Ultrasonic sensor
hc-sr04 = "0.1"
bno055 = { version = "0.3", features = ["std"] }
htu2xd = "0.1"
pwm-pca9685 = "0.3"

log = "0.4"
mint = "0.5"
