[package]
name = "sensors"
version = "1.0.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

### Sensors
linux-embedded-hal = { version = "0.4.0", default-features = false, features = ["gpio_cdev", "i2c"] }
hc-sr04 = "0.1.2"
bno055 = { version = "0.4.0", features = ["std"] }
#htu21df-sensor = { version = "0.1.4", features = ["std"] }
serialport = { version = "4", default-features = false }
anyhow = { workspace = true }

# Serialization
serde = { workspace = true }
serde_with = { workspace = true }

strum = "0.26.2"
tracing = { workspace = true }
mint = { workspace = true }
tokio = "1.47.1"
